language: php
php:
    - '7.2'
    - nightly

install:
    - composer install
    - curl -O http://get.sensiolabs.org/sami.phar

script:
    - vendor/bin/phpunit
    - php sami.phar update ./sami.php

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: 'build'
    on:
        branch: master
